[build]
  publish = "dist"
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  
[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "https://pump.koh.lol/*"
  to = "https://pump.fun/coin/ELehFFYywLvfxCNVgxesCecYPtk4KcM2RYpor6H3AasN"
  status = 301
  force = true