[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "https://pump.koh.lol/*"
  to = "https://pump.fun/coin/ELehFFYywLvfxCNVgxesCecYPtk4KcM2RYpor6H3AasN"
  status = 301
  force = true